name: mobile
description: "Amateur radio toolbox."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_web_auth_2: ^5.0.1
  fl_chart: ^1.1.1
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  file_picker: ^8.1.7
  http: ^1.6.0
  crypto: ^3.0.0
  orbit: ^0.0.15
  latlng: ^2.0.7
  geolocator: ^14.0.2
  permission_handler: ^12.0.3
  sensors_plus: ^7.0.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: system
