server {
    listen 80;
    server_name id.hamcy.work;
    absolute_redirect off;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $openoidc_upstream openoidc:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;

    location / {
        proxy_pass http://$openoidc_upstream;
    }
}

server {
    listen 81;
    server_name id.hamcy.work;
    absolute_redirect off;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $openoidc_upstream openoidc:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;

    location / {
        proxy_pass http://$openoidc_upstream;
    }
}

server {
    listen 82;
    server_name beacon.hamcy.work;
    absolute_redirect off;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $beacon_api_upstream beacon-api:3002;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;

    location = / {
        return 302 /admin;
    }

    location / {
        proxy_pass http://$beacon_api_upstream;
    }
}
